In [1]:
import numpy as np
np.__version__


'1.14.3'

In [2]:
a = 5
type(a)


int

In [3]:
int_list = list(range(10))
int_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
str_list = [str(i) for i in int_list]
str_list

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
int_arr = np.array(int_list)
print(int_arr)
print(int_arr * 2)


[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [9]:
print("int_arr ndim: ", int_arr.ndim)
print("int_arr shape: ", int_arr.shape)
print("int_arr size:", int_arr.size)
print("int_arr dtype: ", int_arr.dtype)

int_arr ndim:  1
int_arr shape:  (10,)
int_arr size: 10
int_arr dtype:  int32


In [12]:
arr_2d = np.zeros((3,5))
arr_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
(1, 2, 3)

(1, 2, 3)

In [18]:
arr_2d.shape
arr_float_3d = np.ones((3, 2, 4))
arr_float_3d.shape

(3, 2, 4)

In [19]:
arr_float_3d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [20]:
arr_float_3d[0, :, :]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])